# fly.toml app configuration file generated for secure-auth on 2025-07-07T14:58:42Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#



app = "secure-auth-prod"
kill_signal = "SIGTERM"
primary_region = "fra"

[env]
DATABASE_PATH = "/mnt/name/name.db"
PHX_HOST = "secure-auth-prod.fly.dev"
PORT = "8080"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_080
min_machines_running = 0
processes = [ "app" ]

  [http_service.concurrency]
  hard_limit = 1_000
  soft_limit = 1_000
  type = "connections"

[[mounts]]
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "10GB"
auto_extend_size_threshold = 80
destination = "/mnt/name"
source = "name"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"