# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Erlang & Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.17'   # match your local
          otp-version: '27'        # match your local

      - name: Cache deps/_build
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install deps
        run: mix deps.get

      - name: Prepare test DB (SQLite file)
        run: |
          MIX_ENV=test mix ecto.create
          MIX_ENV=test mix ecto.migrate

      - name: Run tests
        run: MIX_ENV=test mix test --color --warnings-as-errors
